config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'items' => 'item#index', as: :items
  get 'items/new' => 'item#new', as: :new_item
  get 'items/:id' => 'item#show', as: :item
  post 'items' => 'item#create', as: :create_item
  delete 'items/:id' => 'item#destroy', as: :destroy_item
  post 'items/:id/toggle' => 'item#toggle', as: :toggle_item
  get 'items/:id/edit' => 'item#show', as: :edit_item
  patch 'items/:id/edit' => 'item#show', as: :save_item
  get 'items/:id/up' => 'item#move_up', as: :move_item_up
  get 'items/:id/down' => 'item#move_down', as: :move_item_down

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>DoozerCore</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- Wrap all page content here -->
    <div id="wrap">
      <!-- Fixed navbar -->
      <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Doozer</a>
          </div>
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "All Lists", items_path %></li>
              <li><%= link_to "New List", new_item_path %></li>
                <% if current_user %>
                <li>
                  <%= link_to "Sign out", signout_path, id: "sign_out" %>
                </li>
                <% else %>
                <li>
                  <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
                </li>
                <% end %>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
      <div class='container'>

<% if flash[:notice] %>
<div class="alert alert-info" role="alert"><%= flash[:notice] %></div>
<% end %>

<% if flash[:error] %>
<div class="alert alert-danger" role="alert"><%= flash[:error] %></div>
<% end %>

<%= yield %>

</body>
</html>